/* tests/l3-notifications.test.mjs - the spoiler rule, proved rather than asserted.
 *
 * NOTHING HERE IS INVENTED DATA AND NO FIXTURE WAS WRITTEN.
 * Every notification string this file checks was generated by pushing the REAL
 * output of `src/lib/parse.ts` and `src/lib/detect.ts`, run over the three
 * captured ESPN games in `fixtures/`, through the same copy functions the screen
 * uses. The one thing typed by hand is Sofascore's own priming copy, read off
 * reference/sofascore-teardown/screens/IMG_5203.PNG, and it is there as a
 * POSITIVE CONTROL: a leak test that cannot fail is not a test.
 *
 *   node --test tests/l3-notifications.test.mjs
 *
 * WHY THE LOADER HOOK. The screen module is browser code and imports
 * '/components/states.js' - a server-absolute specifier Node cannot resolve, and
 * importing it raw is the exact crash tools/preview.mjs documents at its top. A
 * resolve hook maps '/components/*' onto public/ so the real module, unmodified,
 * can be tested. Nothing is copied, stubbed or re-declared.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { register } from 'node:module';
import { readFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const FIX = join(ROOT, 'fixtures');

register('data:text/javascript,' + encodeURIComponent(
  `const P = ${JSON.stringify(pathToFileURL(join(ROOT, 'public')).href)};
   export async function resolve(spec, ctx, next) {
     if (spec.startsWith('/components/') || spec.startsWith('/screens/')) return next(P + spec, ctx);
     return next(spec, ctx);
   }`), import.meta.url);

const { parsePlays } = await import('../src/lib/parse.ts');
const { detect } = await import('../src/lib/detect.ts');
const L3 = await import('../public/screens/l3-notifications.screen.js');

const {
  leaks, notify, plan, matchup, heldBody, callSettledBody, finalBody,
  alertsFromSummary, alertsFromDetections, notificationTitle,
  STATELESS, HELD_KINDS, DEFAULT_PREFS, GENERIC_SAFE
} = L3;

const FIXTURES = [
  'real-utep-at-ou-260905-final.json',
  'real-ball-at-osu-260905-final.json',
  'real-bois-at-ore-260905-final.json'
];

const TEAMS = JSON.parse(readFileSync(join(FIX, 'teams.json'), 'utf8'));
const DELAY = 45000;

/** Raw captured summary -> what detect.ts needs. Reads the feed's own fields and
 *  classifies nothing; identical in kind to tests/detect.test.mjs's reader. */
function readFixture(name) {
  const raw = JSON.parse(readFileSync(join(FIX, name), 'utf8'));
  const comp = raw.header.competitions[0];
  const home = comp.competitors.find((c) => c.homeAway === 'home');
  const away = comp.competitors.find((c) => c.homeAway === 'away');
  const facts = {
    homeTeamId: home.team.id, awayTeamId: away.team.id,
    abbrev: { [home.team.id]: home.team.abbreviation, [away.team.id]: away.team.abbreviation },
    score: {}, endYardsToGoal: {}, scoring: {}, turnover: {}, espnType: {}
  };
  const wallclock = {};
  for (const drive of raw.drives.previous) {
    for (const p of drive.plays || []) {
      facts.score[p.id] = { home: Number(p.homeScore), away: Number(p.awayScore) };
      facts.endYardsToGoal[p.id] = p.end && p.end.yardsToEndzone != null ? Number(p.end.yardsToEndzone) : null;
      facts.scoring[p.id] = Boolean(p.scoringPlay);
      facts.turnover[p.id] = Boolean(p.isTurnover);
      facts.espnType[p.id] = (p.type || {}).text || '';
      wallclock[p.id] = p.wallclock ? Date.parse(p.wallclock) : null;
    }
  }
  const plays = parsePlays(raw);
  const detections = detect(plays, facts);
  const read = alertsFromSummary(raw, TEAMS);
  return { name, raw, plays, facts, detections, wallclock, ctx: read.ctx, readerAlerts: read.alerts };
}

const GAMES = FIXTURES.map(readFixture);
const ALL_ON = {};
for (const k of Object.keys(DEFAULT_PREFS)) ALL_ON[k] = true;
for (const e of ['punt', 'kickoff', 'fourth_down', 'red_zone']) ALL_ON[e] = true;

/* ================================================================= */

test('POSITIVE CONTROL - Sofascore\'s own priming copy is caught as a leak', () => {
  /* The three sample alerts on IMG_5203, transcribed from the screen. Every one
   * of them carries live state in the body, which for a delayed app is fatal. */
  const theirs = [
    "61' goal: [1] - 0 L. Modric",
    'Q2 started: 31 - 28',
    'Finished: 2 - 3 Alcaraz'
  ];
  for (const s of theirs) {
    const bad = leaks(s);
    assert.ok(bad.length > 0, `guard did not catch ${JSON.stringify(s)}`);
    console.log(`    caught ${JSON.stringify(s)} ->`, bad.join(', '));
  }
  /* And the shapes it must catch that theirs happen not to use. */
  assert.ok(leaks('Oregon 34-27').includes('digit'));
  assert.ok(leaks('Boise State just scored a touchdown').includes('touchdown'));
  assert.ok(leaks('Oregon lead by seven').length >= 2);   // 'lead' + 'seven'
  assert.ok(leaks('Your call landed').includes('landed'));
  assert.ok(leaks('Oregon won').includes('won'));
  assert.ok(leaks('Madsen intercepted').includes('intercepted'));
  /* And the line that must survive it. */
  assert.deepEqual(leaks('Something just happened in Boise State at Oregon. Open the app when you are ready.'), []);
});

test('every stateless string in the table is clean, against all 760 real teams', () => {
  const teams = Object.values(TEAMS.teams);
  assert.equal(teams.length, 760);
  let substituted = 0;
  const offenders = [];
  for (let i = 0; i < teams.length; i++) {
    const away = teams[i];
    const home = teams[(i + 1) % teams.length];
    const ctx = { awayShort: away.short, homeShort: home.short,
                  awayAbbrev: away.abbrev, homeAbbrev: home.abbrev };
    for (const kind of Object.keys(STATELESS)) {
      const body = STATELESS[kind](ctx);
      const n = notify(kind, body, { holdsState: false, at: 1, delayMs: DELAY, ctx });
      assert.deepEqual(leaks(n.body), [], `${kind} leaked for ${away.abbrev}/${home.abbrev}: ${n.body}`);
      if (n.body !== body) { substituted++; offenders.push(`${kind} · ${away.short} at ${home.short}`); }
    }
  }
  console.log(`    ${teams.length} teams x ${Object.keys(STATELESS).length} strings ` +
              `= ${teams.length * Object.keys(STATELESS).length} bodies, ${substituted} substituted`);
  if (offenders.length) console.log('    substituted:', offenders.slice(0, 5).join(' | '));
});

test('THE SPOILER RULE, over every real detection in all three fixtures', () => {
  let held = 0, stateless = 0, checked = 0;
  for (const g of GAMES) {
    const alerts = alertsFromDetections(g.detections, g.wallclock);
    const p = plan(alerts, { delayMs: DELAY, ctx: g.ctx, prefs: ALL_ON });
    assert.ok(p.sent.length > 0, `${g.name} produced no notifications`);
    for (const n of p.sent) {
      checked++;
      /* The Notification shape from src/lib/types.ts, exactly. */
      assert.deepEqual(Object.keys(n).sort(), ['body', 'holdsState', 'kind', 'sendAt']);
      assert.equal(typeof n.kind, 'string');
      assert.equal(typeof n.body, 'string');
      assert.equal(typeof n.holdsState, 'boolean');
      assert.equal(typeof n.sendAt, 'number');
      assert.ok(n.body.length > 0);

      const title = notificationTitle(g.ctx, n);
      if (n.holdsState) {
        held++;
        assert.equal(HELD_KINDS.includes(n.kind), true, `${n.kind} claims to hold state but is not a held kind`);
      } else {
        stateless++;
        /* THE RULE. No score, no result, no player, no digit - in the body OR in
         * the title, because both reach the lock screen. */
        assert.deepEqual(leaks(n.body), [], `LEAK in ${g.name} / ${n.kind}: ${n.body}`);
        assert.deepEqual(leaks(title), [], `LEAK in title of ${g.name} / ${n.kind}: ${title}`);
      }
    }
  }
  console.log(`    ${checked} notifications from real plays: ${held} held, ${stateless} stateless, 0 leaks`);
  assert.ok(held > 0 && checked === held + stateless);
});

test('a held notification waits exactly the delay; a stateless one does not wait at all', () => {
  const g = GAMES[2];
  const alerts = alertsFromDetections(g.detections, g.wallclock);

  /* The invariant, stated so it cannot be satisfied by accident: raising the
   * delay moves the HELD alerts by exactly that much and the stateless ones not
   * at all. Summed over the whole game, sendAt = sum(event time) + delay x held. */
  const base = plan(alerts, { delayMs: 0, ctx: g.ctx, prefs: ALL_ON });
  const heldCount = base.sent.filter((n) => n.holdsState).length;
  const baseSum = base.sent.reduce((s, n) => s + n.sendAt, 0);
  assert.ok(heldCount > 0 && base.sent.length > heldCount,
    'the fixture must produce both kinds for this to prove anything');

  for (const ms of [0, 15000, 45000, 120000]) {
    const p = plan(alerts, { delayMs: ms, ctx: g.ctx, prefs: ALL_ON });
    assert.equal(p.sent.length, base.sent.length);
    assert.equal(p.sent.filter((n) => n.holdsState).length, heldCount);
    assert.equal(p.sent.reduce((s, n) => s + n.sendAt, 0), baseSum + ms * heldCount,
      `delay ${ms} did not move exactly the held alerts`);
    /* Spot-check one identifiable notification of each kind. */
    const td = p.sent.find((n) => n.kind === 'touchdown');
    const b0 = base.sent.find((n) => n.body === td.body);
    assert.equal(td.sendAt - b0.sendAt, ms);
    const now = p.sent.find((n) => !n.holdsState);
    const n0 = base.sent.find((n) => !n.holdsState && n.sendAt === now.sendAt);
    assert.ok(n0, 'a stateless alert moved with the delay - it must not');
  }
  console.log(`    ${base.sent.length} alerts (${heldCount} held, ` +
              `${base.sent.length - heldCount} stateless); held shift exactly, stateless never move`);
});

test('DEDUPE - 17 qualifying plays become one push', () => {
  const g = GAMES.find((x) => x.name.includes('bois-at-ore'));
  const reasons = g.detections.flatMap((d) => d.reasons);
  const close = reasons.filter((r) => r.event === 'close_game');
  assert.equal(close.length, 17, 'the fixture no longer has 17 close_game reasons');
  assert.equal(new Set(close.map((r) => r.key)).size, 1);
  assert.equal(close[0].key, 'close:4');

  const alerts = alertsFromDetections(g.detections, g.wallclock);
  const p = plan(alerts, { delayMs: DELAY, ctx: g.ctx, prefs: ALL_ON });
  const sentClose = p.sent.filter((n) => n.kind === 'close_game');
  assert.equal(sentClose.length, 1, 'close_game was not deduped - 17 pushes would go out');

  /* And the whole game, not just that one event. */
  const distinct = new Set(alerts.map((a) => a.key)).size;
  console.log(`    ${reasons.length} reasons -> ${distinct} distinct keys -> ${p.sent.length} sent, ` +
              `${p.deduped} collapsed (close_game: 17 -> 1)`);
  /* Nothing is lost and nothing is invented: every alert is sent, collapsed,
   * muted, undated or quieted, and it is exactly one of those. */
  assert.equal(p.sent.length + p.deduped + p.muted + p.undated + p.quieted, alerts.length);
  /* Never more pushes than there are distinct moments. Fewer is allowed: two of
   * the 74 keys belong to plays the feed gave no `wallclock` for. */
  assert.ok(p.sent.length <= distinct, 'more pushes than distinct moments');
  assert.equal(new Set(p.sent.map((n) => n.kind + '@' + n.sendAt)).size, p.sent.length);
});

test('the browser feed reader agrees with detect.ts, key for key, on all three fixtures', () => {
  for (const g of GAMES) {
    const detectKeys = { touchdown: new Set(), field_goal: new Set(), close_game: new Set() };
    for (const d of g.detections) {
      for (const r of d.reasons) if (detectKeys[r.event]) detectKeys[r.event].add(r.key);
    }
    const readerKeys = { touchdown: new Set(), field_goal: new Set(), close_game: new Set() };
    for (const a of g.readerAlerts) if (readerKeys[a.event]) readerKeys[a.event].add(a.key);

    for (const ev of Object.keys(detectKeys)) {
      assert.deepEqual([...readerKeys[ev]].sort(), [...detectKeys[ev]].sort(),
        `${g.name}: ${ev} keys differ between the reader and detect.ts`);
    }
    console.log(`    ${g.name.replace('-260905-final.json', '')}: ` +
      `td ${detectKeys.touchdown.size}, fg ${detectKeys.field_goal.size}, close ${detectKeys.close_game.size} - identical`);
  }
});

test('a poisoned stateless body is substituted, never sent', () => {
  const ctx = GAMES[2].ctx;
  const poisoned = 'Q2 started: 31 - 28';
  const n = notify('nudge', poisoned, { holdsState: false, at: 1000, delayMs: DELAY, ctx });
  assert.notEqual(n.body, poisoned);
  assert.deepEqual(leaks(n.body), []);
  assert.equal(n.body, STATELESS.nudge(ctx));
  /* And the floor under the floor: a context whose own team names trip the guard
   * falls all the way through to a line that names nothing. */
  const bad = notify('nudge', poisoned, {
    holdsState: false, at: 1000, delayMs: DELAY,
    ctx: { awayShort: 'Team 7', homeShort: 'Team 9' }
  });
  assert.equal(bad.body, GENERIC_SAFE);
  assert.deepEqual(leaks(bad.body), []);
});

test('a held notification is ALLOWED to name state, and does', () => {
  const g = GAMES[2];
  const alerts = alertsFromDetections(g.detections, g.wallclock);
  const p = plan(alerts, { delayMs: DELAY, ctx: g.ctx, prefs: ALL_ON });
  const withScore = p.sent.filter((n) => n.holdsState && /[0-9]/.test(n.body));
  assert.ok(withScore.length > 5, 'held notifications are not carrying state - the split is pointless');
  const td = p.sent.find((n) => n.kind === 'touchdown');
  assert.ok(td && /Touchdown/.test(td.body));
  console.log('    HELD samples:');
  for (const n of [p.sent.find((x) => x.kind === 'touchdown'),
                   p.sent.find((x) => x.kind === 'field_goal'),
                   p.sent.find((x) => x.kind === 'downs'),
                   p.sent.find((x) => x.kind === 'close_game'),
                   p.sent.find((x) => x.kind === 'big_play')]) {
    if (n) console.log(`      [${n.kind}] ${n.body}`);
  }
  console.log(`      [call_settled] ${callSettledBody({ side: 'pass', landed: true, delta: 25, bank: 118 })}`);
  console.log(`      [call_settled] ${callSettledBody({ side: 'run', landed: false, delta: -10, bank: 83 })}`);
  console.log(`      [call_settled] ${callSettledBody({ side: 'run', landed: null, delta: 0, bank: 93 })}`);
  console.log(`      [final] ${finalBody(g.ctx, g.ctx.finalScore)}`);
  console.log('    STATELESS samples:');
  for (const k of Object.keys(STATELESS)) console.log(`      [${k}] ${STATELESS[k](g.ctx)}`);
});

test('quiet hours drops, it does not queue', () => {
  const g = GAMES[2];
  const alerts = alertsFromDetections(g.detections, g.wallclock);
  const open = plan(alerts, { delayMs: DELAY, ctx: g.ctx, prefs: ALL_ON });
  /* A window covering every hour: nothing may survive it, and nothing may be
   * moved to the far side of it either. */
  const shut = plan(alerts, {
    delayMs: DELAY, ctx: g.ctx, prefs: ALL_ON,
    quiet: { on: true, startHour: 0, endHour: 24 }
  });
  assert.equal(shut.sent.length, 0);
  assert.equal(shut.quieted, open.sent.length);
  for (const n of shut.sent) assert.fail('a quieted alert was queued: ' + n.body);
  console.log(`    ${open.sent.length} alerts -> 0 sent, ${shut.quieted} dropped, 0 queued for later`);
});

test('preferences mute a kind entirely, and the default set is not everything', () => {
  const g = GAMES[2];
  const alerts = alertsFromDetections(g.detections, g.wallclock);
  const all = plan(alerts, { delayMs: DELAY, ctx: g.ctx, prefs: ALL_ON });
  const def = plan(alerts, { delayMs: DELAY, ctx: g.ctx });
  assert.ok(def.sent.length < all.sent.length, 'the default prefs mute nothing');
  assert.equal(def.sent.some((n) => n.kind === 'punt'), false);
  assert.equal(def.sent.some((n) => n.kind === 'kickoff'), false);
  const off = plan(alerts, { delayMs: DELAY, ctx: g.ctx, prefs: { touchdown: false } });
  assert.equal(off.sent.some((n) => n.kind === 'touchdown'), false);
  console.log(`    default ${def.sent.length} sent / ${def.muted} muted; everything on ${all.sent.length} sent`);
});

test('the balance is Marbles, and no purchase language goes near it', () => {
  const src = readFileSync(join(ROOT, 'public', 'screens', 'l3-notifications.screen.js'), 'utf8');
  const css = readFileSync(join(ROOT, 'public', 'screens', 'l3-notifications.css'), 'utf8');
  for (const word of ['credits', 'coins', 'top-up', 'purchase', ' buy ', 'refill']) {
    assert.equal(src.toLowerCase().includes(word), false, `the module says "${word.trim()}"`);
  }
  assert.ok(src.includes('Marbles'));
  assert.ok(callSettledBody({ side: 'pass', landed: true, delta: 25, bank: 118 }).includes('Marbles'));
  /* Contract section 5: no shadows, and read --accent rather than a theme color. */
  assert.equal(css.includes('box-shadow'), false);
  assert.equal(/--maroon|--gold/.test(css), false);
  assert.ok(css.includes('var(--accent)'));
  /* US spelling. */
  assert.equal(/colour|centre|behaviour|\bgrey\b/i.test(src + css), false);
});

test('every declared state renders a string, and full time is never stateless', () => {
  assert.deepEqual(L3.states, [
    'priming', 'prompt-pending', 'granted', 'denied',
    'preferences', 'quiet-hours', 'loading', 'offline', 'error'
  ]);
  assert.ok(HELD_KINDS.includes('final'), 'a stateless full-time alert spoils a one-score finish');
  assert.ok(HELD_KINDS.includes('close_game'));
  assert.equal(Object.keys(STATELESS).includes('final'), false);
  assert.equal(L3.bar, 'reference/sofascore-teardown/screens/IMG_5203.PNG');
  assert.equal(matchup(GAMES[2].ctx), 'Boise State at Oregon');
});
