' Generated by poll-task.ps1. One per sport, so schtasks /TR stays short.
' 0 = hidden window, False = do not wait: the task's own two-minute tick is the
' supervisor, so this exits at once and the poller keeps running.
CreateObject("WScript.Shell").Run ""C:\Users\jstua\AppData\Local\Microsoft\WinGet\Packages\OpenJS.NodeJS.LTS_Microsoft.Winget.Source_8wekyb3d8bbwe\node-v24.18.0-win-x64\node.exe" "C:\Claude\Knowledge\anygiven\tools\poll.mjs" 401872656 --sport nfl --every 10", 0, False
